In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
from scipy.stats import qmc
from os import path
from self_driving_lab_demo.utils.plotting import plot_and_save

In [2]:
bounds = {"x1": [-0.01, 0.01], "x2": [-0.01, 0.01], "x3": [-0.01, 0.01], "x4": [-0.01, 0.01], "x5": [-0.01, 0.01], "x6": [-0.01, 0.01], "x7": [-0.01, 0.01], "x8": [-0.01, 0.01]}
num_samples = 256

In [3]:
from scipy.stats.qmc import Sobol

def get_sobol_samples(bounds, num_samples, seed=None):
    sampler = Sobol(len(bounds), seed=seed)
    samples = sampler.random(num_samples)
    
    l_bounds = [bound[0] for bound in bounds.values()]
    u_bounds = [bound[1] for bound in bounds.values()]
    samples = qmc.scale(samples, l_bounds, u_bounds)
    
    return pd.DataFrame(samples, columns=list(bounds.keys())).round(4)

design_parameter = get_sobol_samples(bounds, num_samples=num_samples, seed=0)
design_parameter

         x1      x2      x3      x4      x5      x6      x7      x8
0    0.0070  0.0086 -0.0027 -0.0027 -0.0072  0.0012 -0.0015 -0.0022
1   -0.0037 -0.0029  0.0047  0.0051  0.0089 -0.0050  0.0084  0.0031
2   -0.0077  0.0032 -0.0069 -0.0094  0.0025 -0.0023 -0.0078  0.0071
3    0.0016 -0.0077  0.0056  0.0021 -0.0010  0.0064  0.0022 -0.0076
4    0.0037  0.0014  0.0022  0.0042 -0.0032  0.0028 -0.0072  0.0088
..      ...     ...     ...     ...     ...     ...     ...     ...
251  0.0037 -0.0041 -0.0095 -0.0053  0.0016 -0.0008  0.0082  0.0069
252  0.0017  0.0054 -0.0028 -0.0085  0.0038 -0.0100 -0.0036 -0.0055
253 -0.0078 -0.0011  0.0046  0.0011 -0.0023  0.0038  0.0067  0.0098
254 -0.0036  0.0003 -0.0074 -0.0044 -0.0060  0.0086 -0.0074  0.0000
255  0.0069 -0.0056  0.0050  0.0066  0.0076 -0.0026  0.0030 -0.0047

[256 rows x 8 columns]

In [4]:
a = design_parameter.apply(np.array, axis=1)
a

0      [0.007, 0.0086, -0.0027, -0.0027, -0.0072, 0.0...
1      [-0.0037, -0.0029, 0.0047, 0.0051, 0.0089, -0....
2      [-0.0077, 0.0032, -0.0069, -0.0094, 0.0025, -0...
3      [0.0016, -0.0077, 0.0056, 0.0021, -0.001, 0.00...
4      [0.0037, 0.0014, 0.0022, 0.0042, -0.0032, 0.00...
                             ...
251    [0.0037, -0.0041, -0.0095, -0.0053, 0.0016, -0...
252    [0.0017, 0.0054, -0.0028, -0.0085, 0.0038, -0....
253    [-0.0078, -0.0011, 0.0046, 0.0011, -0.0023, 0....
254    [-0.0036, 0.0003, -0.0074, -0.0044, -0.006, 0....
255    [0.0069, -0.0056, 0.005, 0.0066, 0.0076, -0.00...
Length: 256, dtype: object

In [5]:
a = design_parameter.apply(np.array, axis=1)
a

0      [0.007, 0.0086, -0.0027, -0.0027, -0.0072, 0.0...
1      [-0.0037, -0.0029, 0.0047, 0.0051, 0.0089, -0....
2      [-0.0077, 0.0032, -0.0069, -0.0094, 0.0025, -0...
3      [0.0016, -0.0077, 0.0056, 0.0021, -0.001, 0.00...
4      [0.0037, 0.0014, 0.0022, 0.0042, -0.0032, 0.00...
                             ...
251    [0.0037, -0.0041, -0.0095, -0.0053, 0.0016, -0...
252    [0.0017, 0.0054, -0.0028, -0.0085, 0.0038, -0....
253    [-0.0078, -0.0011, 0.0046, 0.0011, -0.0023, 0....
254    [-0.0036, 0.0003, -0.0074, -0.0044, -0.006, 0....
255    [0.0069, -0.0056, 0.005, 0.0066, 0.0076, -0.00...
Length: 256, dtype: object

In [6]:
# Generate three additional 1D arrays with length 128
array0 = np.full(8,0)
array1 = [0.01, 0.01, 0.01, 0.01, -0.01, -0.01, -0.01, -0.01 ]
array2 = [-0.01, -0.01, -0.01, -0.01, 0.01, 0.01, 0.01, 0.01]

In [7]:
# Append arrays as rows to the DataFrame
design_parameter.loc[len(design_parameter)] = array0
design_parameter.loc[len(design_parameter)] = array1
design_parameter.loc[len(design_parameter)] = array2

# # Reset index if needed
# sobol_samples.reset_index(drop=True, inplace=True)
design_parameter

         x1      x2      x3      x4      x5      x6      x7      x8
0    0.0070  0.0086 -0.0027 -0.0027 -0.0072  0.0012 -0.0015 -0.0022
1   -0.0037 -0.0029  0.0047  0.0051  0.0089 -0.0050  0.0084  0.0031
2   -0.0077  0.0032 -0.0069 -0.0094  0.0025 -0.0023 -0.0078  0.0071
3    0.0016 -0.0077  0.0056  0.0021 -0.0010  0.0064  0.0022 -0.0076
4    0.0037  0.0014  0.0022  0.0042 -0.0032  0.0028 -0.0072  0.0088
..      ...     ...     ...     ...     ...     ...     ...     ...
254 -0.0036  0.0003 -0.0074 -0.0044 -0.0060  0.0086 -0.0074  0.0000
255  0.0069 -0.0056  0.0050  0.0066  0.0076 -0.0026  0.0030 -0.0047
256  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000
257  0.0100  0.0100  0.0100  0.0100 -0.0100 -0.0100 -0.0100 -0.0100
258 -0.0100 -0.0100 -0.0100 -0.0100  0.0100  0.0100  0.0100  0.0100

[259 rows x 8 columns]

In [8]:
a = design_parameter.apply(np.array, axis=1)
a

0      [0.007, 0.0086, -0.0027, -0.0027, -0.0072, 0.0...
1      [-0.0037, -0.0029, 0.0047, 0.0051, 0.0089, -0....
2      [-0.0077, 0.0032, -0.0069, -0.0094, 0.0025, -0...
3      [0.0016, -0.0077, 0.0056, 0.0021, -0.001, 0.00...
4      [0.0037, 0.0014, 0.0022, 0.0042, -0.0032, 0.00...
                             ...
254    [-0.0036, 0.0003, -0.0074, -0.0044, -0.006, 0....
255    [0.0069, -0.0056, 0.005, 0.0066, 0.0076, -0.00...
256             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
257    [0.01, 0.01, 0.01, 0.01, -0.01, -0.01, -0.01, ...
258    [-0.01, -0.01, -0.01, -0.01, 0.01, 0.01, 0.01,...
Length: 259, dtype: object

In [9]:
# import matplotlib.pyplot as plt

# plt.scatter(sobol_samples.x1,sobol_samples.x2, label = '12')
# plt.scatter(sobol_samples.x2,sobol_samples.x3, label = '23')
# plt.scatter(sobol_samples.x3,sobol_samples.x4, label = '34')
# plt.scatter(sobol_samples.x4,sobol_samples.x5, label = '45')
# plt.scatter(sobol_samples.x5,sobol_samples.x6, label = '56')
# plt.scatter(sobol_samples.x6,sobol_samples.x7, label = '67')
# plt.scatter(sobol_samples.x7,sobol_samples.x8, label = '78')
# plt.scatter(sobol_samples.x8,sobol_samples.x1, label = '81')
# plt.legend(loc=(1.01,0.53))

In [10]:
design_parameter.to_excel('design_parmeter.xlsx')